### ISSUE TITLE
Some errors about dimension when running examples

### ISSUE THREAD

**Issue by yizhezhang0418** [umautobots/LONER#10]
Hi!
Thanks for your amazing work!
I am currently trying to run LONER.However,I meet some questions when I was running the demo in the example file.
![截图 2023-12-11 16-14-02](https://github.com/umautobots/LONER/assets/140721585/ee3c6967-ff0d-42c3-9bdf-ecfc11e58e71)
Are you familiar with the problem?
I use the docker environment you provide.And my Ubuntu version is 22.04.

Thanks!
Alex Zhang

**Comment by sethgi** [comment]
Can you send the full terminal output?

**Comment by sethgi** [comment]
Also can you share the contents of the groundtruth trajectory file you're using? I suspect that this is an issue with time sync, I confirmed this sequence runs fine on my machine though.

**Comment by yizhezhang0418** [comment]
Thanks for your reply!
Here is my gt trajectory,and it is downloading from your data website.
![截图 2023-12-18 21-46-09](https://github.com/umautobots/LONER/assets/140721585/62a15b9e-ed87-4523-a5cf-0f6665bcd80f)
Are there any problem?
Thanks!

**Comment by yizhezhang0418** [comment]
And there is the full terminal output.
![截图 2023-12-18 21-55-27](https://github.com/umautobots/LONER/assets/140721585/275373b7-7487-47d3-bcfe-cd552bd894ad)

**Comment by sethgi** [comment]
That ground truth trajectory looks to be from the MCR slow sequence, but the bag you're using is from the normal speed sequence. That could be your issue.

**Comment by yizhezhang0418** [comment]
Sorry......It is my fault.I give the wrong picture to you...
The correct picture is here.
![截图 2023-12-18 23-27-38](https://github.com/umautobots/LONER/assets/140721585/16247095-870c-4f52-b480-9b8c99e45aa0)
And the bag file is here.
![截图 2023-12-18 23-30-41](https://github.com/umautobots/LONER/assets/140721585/ea2dd4e6-f254-4f11-93a3-7a8cb94567a9)

**Comment by sethgi** [comment]
Can you show me groundtruth_traj, since that's the one you refer to in the `mcr.yaml` file?

**Comment by yizhezhang0418** [comment]
Thanks for your reply!
I have solved this issue,since I used the wrong bag file!

**Comment by sethgi** [comment]
Glad it worked out!

**Comment by Joy881007** [comment]
@yizhezhang0418  Hi! May I ask you which bag file did you use to solved this problem?
I'm trying to run LONER using canteen dataset and meet the same question.
![Screenshot from 2023-12-20 14-37-46](https://github.com/umautobots/LONER/assets/92676237/f9196c4a-9d3f-43bb-a6a3-d9723c8ec180)
And the bag file I use is 20220216_canteen_day_ref_prcv2022.bag from website
<img width="286" alt="截圖 2023-12-20 下午3 09 34" src="https://github.com/umautobots/LONER/assets/92676237/55589408-6ab7-4da9-a94f-c0e45a83d7fd">

**Comment by yizhezhang0418** [comment]
Hi,maybe you need to use 20220216_canteen_day instead of 20220216_canteen_day_ref_prcv2022.bag.

**Comment by Joy881007** [comment]
Thanks for your reply!
I have solved the problem by following your suggestion!

**Comment by Joy881007** [comment]
Thanks for your reply!
I use 20220216_canteen_day instead and it works!
