### ISSUE TITLE
Can not pull the image from the dockerhub

### ISSUE THREAD

**Issue by jiatianluo** [umautobots/LONER#15]
I tried to pull the image following your advice, but I was still unable to succeed due to unstable network issues (which I believe may be related to my location in China). Docker Hub should host certain dependencies and configuration information. Now, I am considering configuring these manually. Is this feasible? If so, could you please provide me with some steps? Thank you very much! Additionally, regarding my computer information, my computer's operating system is Windows 11, and I am using an Ubuntu 20.04 virtual machine. Furthermore, my GPU has a memory of 16.9GB. I have not downloaded CUDA yet, and I am not sure if my GPU can support me in downloading CUDA and running this project. I hope you can tell me.

**Comment by sethgi** [comment]
Please see this answer: https://github.com/umautobots/LONER/issues/13#issuecomment-1887566989
