### ISSUE TITLE
OSError: Could not find compatible tinycudann extension for compute capability 61.

### ISSUE THREAD

**Issue by RoseWillow** [umautobots/LONER#6]
![2023-11-05 15-36-14屏幕截图](https://github.com/umautobots/LONER/assets/34000284/6f84fc6e-7f14-49b0-93c7-731064cf054d)

**Comment by sethgi** [comment]
Please uninstall tinycudann and re-install for the correct compute capability. There are a couple issues on the tcnn github that might be helpful:

https://github.com/NVlabs/tiny-cuda-nn/issues/330#issuecomment-1707935743

Note that to uninstall you may need to manually `sudo rm -rf /opt/conda/lib/python3.8/site-packages/tinycudann*`

**Comment by RoseWillow** [comment]
That's helpful, Thank you very much!
