### ISSUE TITLE
running outside  of docker

### ISSUE THREAD

**Issue by Zhangjyhhh** [umautobots/LONER#8]
Thanks for your excellent works!!!
I want to run this code outside of docker, how should i config environment? I'd appreciate it  if you could tell me

**Comment by sethgi** [comment]
Thanks for the comment... I'll add this to my to-do list and will hopefully get to it in the next week or two.

For now, I'd encourage you to look through our dockerfiles, which can serve as temporary "documentation" for the dependencies you need to install. The big stuff is pytorch (we use pytorch 1), cuda, ROS, and tiny-cuda-nn. Aside from that it will be lots of little python packages.

**Comment by Zhangjyhhh** [comment]
thanks a lot !!

**Comment by whwh747** [comment]
Hello, is there any documentation available for running outside of Docker? @sethgi
